MODULES = puct_edge
EXTENSION = puct_edge
DATA = puct_edge--1.0.sql
PGFILEDESC = "puct_edge - in-database packed-edge backup patch for PUCT Book Builder"

PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
